### ISSUE TITLE
Redundant extension placement

### ISSUE THREAD

**Issue by ImportTaste** [herp-a-derp/xA-Scraper#47]
>Out of curiosity, if you try to browse to the relevant URL, does it work?
>
>If the page works properly, but fetching it fails, I'd need to see the actual page to figure out what's going on. 
>
>You can e-mail me about it if you don't want to post URLs publicly. anything \<at\> fake-url \<dot\> com will get to me.
>
>_Originally posted by @herp-a-derp in https://github.com/herp-a-derp/xA-Scraper/issues/46#issuecomment-529147940_

The actual URL is not important. See how many times 'swf' occurs. It's placing the extension redundantly. It's exactly in this pattern:

`http://d.facdn.net` **swf** `/art/herpaderp/1234567890/1234567890.` **swf** `herpaderp_imodifiedthisurl_video.` **swf**

**Comment by herp-a-derp** [comment]
Oh, yeah. that's intentional. 

Basically, you get `<filename it's served as><filename derived from webpage>`.
