### ISSUE TITLE
Filename weirdness

### ISSUE THREAD

**Issue by ImportTaste** [herp-a-derp/xA-Scraper#54]
With fAGet especially, I've noticed that a lot of the images receive the technically valid but hardly used extensions `.jpe` and `.jfif` (though this second one is very rare). They should be given a jpg extension instead.

Additionally, while dAGet retrieves valid images, but the filenames don't reflect the submission at all. Instead it's the filename created by their new CDN, which will look like a random string of letters and numbers.

**Comment by ImportTaste** [comment]
I just realized what the pronunciation of `fAGet` must be...

**Comment by herp-a-derp** [comment]
> I just realized what the pronunciation of `fAGet` must be...

Goddammit.
